//Command: xaw2verilog -intstyle /home/zeus/zet/impl/spartan3an-sk/ise/clocks.xaw -st clocks.v
//Design Name: clocks
//Device: xc3s700an-4fgg484
//
// Module clocks
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// Modified by Zeus Gómez 
// Period Jitter (unit interval) for block DCM_SP_INST = 0.03 UI
// Period Jitter (Peak-to-Peak) for block DCM_SP_INST = 1.03 ns
`timescale 1ns / 1ps

module clocks (
    input  clk50M_pad,
    input  reset,
    output clk50M,
    output clk25M,
    output clk12M,
    output locked
  );

  wire CLKDV_BUF;
  wire CLKFB_IN;
  wire CLKFX_BUF;
  wire CLKIN_IBUFG;
  wire CLK0_BUF;
  wire GND_BIT;

  assign GND_BIT = 0;
  assign clk50M = CLKFB_IN;

  BUFG CLKDV_BUFG_INST (.I(CLKDV_BUF),
                        .O(clk12M));
  BUFG CLKFX_BUFG_INST (.I(CLKFX_BUF),
                        .O(clk25M));
  IBUFG CLKIN_IBUFG_INST (.I(clk50M_pad), 
                          .O(CLKIN_IBUFG));
  BUFG CLK0_BUFG_INST (.I(CLK0_BUF), 
                       .O(CLKFB_IN));
  DCM_SP DCM_SP_INST (.CLKFB(CLKFB_IN), 
                      .CLKIN(CLKIN_IBUFG), 
                      .DSSEN(GND_BIT), 
                      .PSCLK(GND_BIT), 
                      .PSEN(GND_BIT), 
                      .PSINCDEC(GND_BIT), 
                      .RST(reset), 
                      .CLKDV(CLKDV_BUF), 
                      .CLKFX(CLKFX_BUF), 
                      .CLKFX180(), 
                      .CLK0(CLK0_BUF), 
                      .CLK2X(), 
                      .CLK2X180(), 
                      .CLK90(), 
                      .CLK180(), 
                      .CLK270(), 
                      .LOCKED(locked), 
                      .PSDONE(), 
                      .STATUS());
  defparam DCM_SP_INST.CLK_FEEDBACK = "1X";
  defparam DCM_SP_INST.CLKDV_DIVIDE = 4.0;
  defparam DCM_SP_INST.CLKFX_DIVIDE = 4;
  defparam DCM_SP_INST.CLKFX_MULTIPLY = 2;
  defparam DCM_SP_INST.CLKIN_DIVIDE_BY_2 = "FALSE";
  defparam DCM_SP_INST.CLKIN_PERIOD = 20.000;
  defparam DCM_SP_INST.CLKOUT_PHASE_SHIFT = "NONE";
  defparam DCM_SP_INST.DESKEW_ADJUST = "SYSTEM_SYNCHRONOUS";
  defparam DCM_SP_INST.DFS_FREQUENCY_MODE = "LOW";
  defparam DCM_SP_INST.DLL_FREQUENCY_MODE = "LOW";
  defparam DCM_SP_INST.DUTY_CYCLE_CORRECTION = "TRUE";
  defparam DCM_SP_INST.FACTORY_JF = 16'hC080;
  defparam DCM_SP_INST.PHASE_SHIFT = 0;
  defparam DCM_SP_INST.STARTUP_WAIT = "FALSE";
endmodule